import type { Preset } from './types';

export const PHOTOGRAPHY_PRESETS: Preset[] = [
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Warm, soft lighting reminiscent of sunset',
    category: 'photography',
    subcategory: 'landscape',
    tags: ['warm', 'sunset', 'orange', 'soft'],
    icon: '🌅',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'colorBalance',
        params: {
          shadows: [0.1, 0.05, -0.1],
          midtones: [0.15, 0.08, -0.05],
          highlights: [0.2, 0.1, 0],
        },
        opacity: 0.8,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'vibrance',
        params: { vibrance: 0.3 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'glow',
        effect: 'bloom',
        params: { intensity: 0.3, radius: 30, threshold: 0.7 },
        opacity: 0.5,
        blendMode: 'screen',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.3, softness: 0.6, size: 0.7 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
    variants: [
      { name: 'Subtle', intensity: 0.5, paramOverrides: {} },
      { name: 'Strong', intensity: 1.5, paramOverrides: {} },
    ],
  },
  {
    id: 'dramatic-sky',
    name: 'Dramatic Sky',
    description: 'High contrast landscape with enhanced clouds',
    category: 'photography',
    subcategory: 'landscape',
    tags: ['dramatic', 'contrast', 'clouds', 'landscape'],
    icon: '⛈️',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: -0.05, contrast: 0.4 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.2, lightness: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'sharpen',
        params: { intensity: 0.4 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.5, softness: 0.4, size: 0.6 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'soft-portrait',
    name: 'Soft Portrait',
    description: 'Flattering skin tones with soft glow',
    category: 'photography',
    subcategory: 'portrait',
    tags: ['portrait', 'soft', 'skin', 'beauty'],
    icon: '👤',
    version: '1.0.0',
    layers: [
      {
        type: 'blur',
        effect: 'gaussian',
        params: { radius: 3, quality: 'high' },
        opacity: 0.2,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'colorBalance',
        params: { shadows: [0, 0, 0], midtones: [0.05, 0.02, 0], highlights: [0.08, 0.04, 0.02] },
        opacity: 0.7,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'glow',
        effect: 'bloom',
        params: { intensity: 0.2, radius: 40, threshold: 0.8 },
        opacity: 0.4,
        blendMode: 'screen',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.25, softness: 0.7, size: 0.8 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
    adaptiveParams: [
      {
        layerIndex: 0,
        paramName: 'radius',
        adaptTo: 'brightness',
        mapping: { inputMin: 0.3, inputMax: 0.7, outputMin: 2, outputMax: 5, curve: 'ease' },
      },
    ],
  },
  {
    id: 'urban-grit',
    name: 'Urban Grit',
    description: 'Gritty street photography style',
    category: 'photography',
    subcategory: 'street',
    tags: ['urban', 'gritty', 'street', 'contrast'],
    icon: '🏙️',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0, contrast: 0.35 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: -0.15, lightness: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'grain',
        params: { amount: 0.08, scale: 1.5, speed: 0, monochrome: true },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'sharpen',
        params: { intensity: 0.6 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.45, softness: 0.3, size: 0.5 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
];

export const VIDEO_PRESETS: Preset[] = [
  {
    id: 'teal-orange',
    name: 'Teal & Orange',
    description: 'Hollywood blockbuster color grading',
    category: 'video',
    subcategory: 'cinematic',
    tags: ['cinema', 'blockbuster', 'teal', 'orange', 'hollywood'],
    icon: '🎬',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'colorBalance',
        params: {
          shadows: [-0.15, 0.05, 0.2],
          midtones: [0, 0, 0.05],
          highlights: [0.2, 0.1, -0.1],
        },
        opacity: 0.85,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.15, lightness: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0, contrast: 0.15 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.2, softness: 0.5, size: 0.7 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'vhs-retro',
    name: 'VHS',
    description: 'Authentic 80s VHS tape look',
    category: 'video',
    subcategory: 'retro',
    tags: ['vhs', 'retro', '80s', 'vintage', 'tape'],
    icon: '📼',
    version: '1.0.0',
    layers: [
      {
        type: 'stylize',
        effect: 'chromaticAberration',
        params: { intensity: 0.015, angle: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'scanlines',
        params: { amount: 0.15, frequency: 480 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'grain',
        params: { amount: 0.12, scale: 0.8, speed: 30, monochrome: false },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.1, lightness: 0.05 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'blur',
        effect: 'gaussian',
        params: { radius: 0.5, quality: 'low' },
        opacity: 0.3,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'horror-mood',
    name: 'Horror',
    description: 'Creepy desaturated look for horror content',
    category: 'video',
    subcategory: 'genre',
    tags: ['horror', 'creepy', 'dark', 'desaturated'],
    icon: '👻',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: -0.5, lightness: -0.1 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: -0.1, contrast: 0.3 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'tint',
        params: { tintColor: [0.1, 0.15, 0.2], amount: 0.2 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'grain',
        params: { amount: 0.06, scale: 1, speed: 12, monochrome: true },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.6, softness: 0.3, size: 0.4 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'scifi-neon',
    name: 'Sci-Fi Neon',
    description: 'Cyberpunk-inspired neon glow aesthetic',
    category: 'video',
    subcategory: 'genre',
    tags: ['scifi', 'cyberpunk', 'neon', 'futuristic'],
    icon: '🤖',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: -0.15, contrast: 0.4 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'tint',
        params: { tintColor: [0.1, 0.0, 0.2], amount: 0.15 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'glow',
        effect: 'bloom',
        params: { intensity: 0.6, radius: 25, threshold: 0.6 },
        opacity: 0.7,
        blendMode: 'screen',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'chromaticAberration',
        params: { intensity: 0.008, angle: 90 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
];

export const GAMING_PRESETS: Preset[] = [
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    description: 'Retro pixelated game aesthetic',
    category: 'gaming',
    subcategory: 'retro',
    tags: ['pixel', 'retro', '8bit', 'game'],
    icon: '👾',
    version: '1.0.0',
    layers: [
      {
        type: 'distortion',
        effect: 'pixelate',
        params: { amount: 8 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.3, lightness: 0.1 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0.05, contrast: 0.2 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
    variants: [
      { name: '8-bit', intensity: 1, paramOverrides: { '0': { amount: 8 } } },
      { name: '16-bit', intensity: 1, paramOverrides: { '0': { amount: 4 } } },
      { name: '32-bit', intensity: 1, paramOverrides: { '0': { amount: 2 } } },
    ],
  },
  {
    id: 'crt-screen',
    name: 'CRT Screen',
    description: 'Classic CRT monitor effect',
    category: 'gaming',
    subcategory: 'retro',
    tags: ['crt', 'retro', 'monitor', 'arcade'],
    icon: '🖥️',
    version: '1.0.0',
    layers: [
      {
        type: 'noise',
        effect: 'scanlines',
        params: { amount: 0.25, frequency: 600 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'chromaticAberration',
        params: { intensity: 0.003, angle: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'glow',
        effect: 'bloom',
        params: { intensity: 0.15, radius: 8, threshold: 0.7 },
        opacity: 0.5,
        blendMode: 'screen',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'vignette',
        params: { intensity: 0.35, softness: 0.2, size: 0.6 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'cel-shading',
    name: 'Cel Shading',
    description: 'Cartoon/anime style cel shading',
    category: 'gaming',
    subcategory: 'stylize',
    tags: ['cel', 'cartoon', 'anime', 'toon'],
    icon: '✏️',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'posterize',
        params: { levels: 6 },
        opacity: 0.8,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'edges',
        params: { intensity: 0.4, threshold: 0.2 },
        opacity: 0.6,
        blendMode: 'multiply',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.2, lightness: 0.05 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
];

export const MOTION_PRESETS: Preset[] = [
  {
    id: 'speed-blur',
    name: 'Speed Blur',
    description: 'Motion blur for fast movement',
    category: 'motion',
    tags: ['speed', 'motion', 'blur', 'action'],
    icon: '💨',
    version: '1.0.0',
    layers: [
      {
        type: 'blur',
        effect: 'motion',
        params: { radius: 30, angle: 0 },
        opacity: 0.6,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0.05, contrast: 0.15 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'impact-flash',
    name: 'Impact Flash',
    description: 'Bright flash for impact moments',
    category: 'motion',
    tags: ['impact', 'flash', 'hit', 'action'],
    icon: '💥',
    version: '1.0.0',
    layers: [
      {
        type: 'glow',
        effect: 'bloom',
        params: { intensity: 2, radius: 50, threshold: 0.3 },
        opacity: 1,
        blendMode: 'add',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0.5, contrast: 0.3 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'chromaticAberration',
        params: { intensity: 0.02, angle: 45 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'glitch-transition',
    name: 'Glitch',
    description: 'Digital glitch effect for transitions',
    category: 'motion',
    subcategory: 'transition',
    tags: ['glitch', 'digital', 'transition', 'effect'],
    icon: '📺',
    version: '1.0.0',
    layers: [
      {
        type: 'stylize',
        effect: 'chromaticAberration',
        params: { intensity: 0.03, angle: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'static',
        params: { amount: 0.2, scale: 2, speed: 60, monochrome: false },
        opacity: 0.4,
        blendMode: 'screen',
        enabled: true,
      },
      {
        type: 'distortion',
        effect: 'wave',
        params: { amount: 10, frequency: 20, phase: 0, animationSpeed: 5 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
];

export const ARTISTIC_PRESETS: Preset[] = [
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft watercolor painting effect',
    category: 'artistic',
    subcategory: 'stylize',
    tags: ['watercolor', 'paint', 'art', 'soft'],
    icon: '🎨',
    version: '1.0.0',
    layers: [
      {
        type: 'blur',
        effect: 'gaussian',
        params: { radius: 2, quality: 'medium' },
        opacity: 0.4,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'stylize',
        effect: 'edges',
        params: { intensity: 0.2, threshold: 0.4 },
        opacity: 0.3,
        blendMode: 'multiply',
        enabled: true,
      },
      {
        type: 'noise',
        effect: 'perlin',
        params: { amount: 0.1, scale: 3, speed: 0, monochrome: true },
        opacity: 0.2,
        blendMode: 'overlay',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: 0.15, lightness: 0.05 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
  {
    id: 'duotone',
    name: 'Duotone',
    description: 'Two-color gradient map effect',
    category: 'artistic',
    subcategory: 'stylize',
    tags: ['duotone', 'gradient', 'stylized', 'modern'],
    icon: '🔵',
    version: '1.0.0',
    layers: [
      {
        type: 'color',
        effect: 'hueSaturation',
        params: { hue: 0, saturation: -1, lightness: 0 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'gradient',
        params: { colorA: [0.1, 0.0, 0.3], colorB: [1.0, 0.4, 0.2] },
        opacity: 1,
        blendMode: 'color',
        enabled: true,
      },
      {
        type: 'color',
        effect: 'brightnessContrast',
        params: { brightness: 0, contrast: 0.2 },
        opacity: 1,
        blendMode: 'normal',
        enabled: true,
      },
    ],
  },
];

export const ALL_PRESETS: Preset[] = [
  ...PHOTOGRAPHY_PRESETS,
  ...VIDEO_PRESETS,
  ...GAMING_PRESETS,
  ...MOTION_PRESETS,
  ...ARTISTIC_PRESETS,
];
